export const forbiddenConst = {
  NOT_ENOUGH_STORE_DREAM: "0401",
  NOT_ENOUGH_STAMP_TO_HAND_OUT: "0402",
  NOT_ENOUGH_COUPON_TO_HAND_OUT: "0403",
  NOT_GIFTABLE_COUPON: "0404",
  NOT_ISSUABLE_DATE_COUPON: "0405",
  ONLY_ISSUABLE_COUPON_IN_FRANCHISE: "0406",
  NOT_ENOUGH_COUPON_TO_ISSUE: "0407",
  NOT_ENOUGH_AVAILABLE_STAMP_CNT: "0408",
};
